name: Your Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: alpine:latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        apk add coreutils bash wget git build-base meson glib-dev cairo-dev  \
          pango-dev libxkbcommon-dev libxcb-dev gdk-pixbuf-dev xcb-util-dev \
          xcb-util-wm-dev xcb-util-xrm-dev xcb-util-cursor-dev librsvg-dev \
          startup-notification-dev flex bison ronn cppcheck check-dev \
          xkeyboard-config-dev xcb-util-keysyms-dev desktop-file-utils

        chmod +x ./rofi-appimage.sh && ./rofi-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
